services:
  postgres:
    image: postgres:17
    container_name: Neo-MES-2-db-postgres
    volumes:
      - Neo-MES-2-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "veYjzlrAQlYif1oagwllkvVc07rcrsIG"
      POSTGRES_USER: "NeoMES2"
      POSTGRES_DB: "NeoMES2"
    ports:
      - "127.0.0.1:12100:5432"
    restart: always
    networks:
      - Neo-MES-2_network

  backend:
    build:
      context: .
      dockerfile: ./neo-mes-2-rest-api/Dockerfile
    container_name: neo-mes-2-rest-api
    ports:
      - "127.0.0.1:12010:80"
    env_file:
      - ./neo-mes-2-rest-api/.env
    volumes:
      - ./media:/app/media
    restart: always
    networks:
      - Neo-MES-2_network

  # Build: docker compose build --build-arg c=development frontend
  frontend:
    build:
      context: .
      dockerfile: ./neo-mes-2-frontend/Dockerfile
      args:
        c: production
    container_name: neo-mes-2-frontend
    ports:
      - "127.0.0.1:12001:80"
    restart: always
    networks:
      - Neo-MES-2_network

volumes:
  Neo-MES-2-postgres-data:
    driver: local

networks:
  Neo-MES-2_network:
    driver: bridge
